### ISSUE TITLE
Get the Windows tests running on Windows again

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OMSimulator#879]
**Is your feature request related to a problem? Please describe.**
We need to get the Windows mingw and msvc tests back into Jenkins and running.

**Describe the solution you'd like**
PR #855 will add mingw and msvc back to Jenkins, but the tests are disabled because they are failing.
See e.g. #878

**Comment by AnHeuermann** [comment]
We activated all tests in #896. Now we need to fix the remaining problems:

As far as I can see we have four classes of problems:
- [ ]  `source="resources\0001_A.fmu">`, will be fixed by #888.
- [ ]   Missing windows binaries for FMUs, I'll add them manually to #896.
- [ ]   OMSimulator.dll can't be found from python, see #897.
- [ ]   TLM having segmentation faults and possible memory leaks
